name: Run Notebooks

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  execute-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install notebook nbconvert ipykernel

    - name: Execute demo.ipynb
      run: |
        jupyter nbconvert --to notebook --execute demo.ipynb --output executed_demo.ipynb

    - name: Execute Welcome_To_Colab.ipynb
      run: |
        jupyter nbconvert --to notebook --execute "Welcome_To_Colab.ipynb" --output "executed_Welcome_To_Colab.ipynb"
